name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1.6'  # LTS
          - '1.8'  # LTS
          - '1.9'
          - '1.10'
          - '1.11'
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        arch:
          - x64
        exclude:
          # 32-bit Julia is not available on macOS
          - os: macos-latest
            arch: x86
          # 32-bit Julia is not available on Windows
          - os: windows-latest
            arch: x86
        include:
          # 32-bit Julia is only available on Linux
          - version: '1.6'
            os: ubuntu-latest
            arch: x86
          - version: '1.8'
            os: ubuntu-latest
            arch: x86

    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}

      - uses: actions/cache@v3
        env:
          cache-name: cache-artifacts
        with:
          path: ~/.julia/artifacts
          key: ${{ runner.os }}-test-${{ env.cache-name }}-${{ hashFiles('**/Project.toml') }}
          restore-keys: |
            ${{ runner.os }}-test-${{ env.cache-name }}-
            ${{ runner.os }}-test-
            ${{ runner.os }}-

      - uses: julia-actions/julia-buildpkg@v1

      - uses: julia-actions/julia-runtest@v1

      - uses: julia-actions/julia-processcoverage@v1

      - uses: codecov/codecov-action@v3
        with:
          file: lcov.info
          fail_ci_if_error: true
